# See docs/examples
# http://doc.gitlab.com/ce/ci/quick_start/README.html
# http://doc.gitlab.com/ce/ci/yaml/README.html

# GitLab CI template for Go tests. Note this installs
# a new working copy of Go in a non-standard path such
# that sudo/root is not needed for the install stage.

# note that this particular install-environment stage
# is overly verbose in order to debug anything tricky
# or weird in your environment - feel free to trim it 
# down as needed

image: alpine:edge

compile-go:
  script:
    - export CURRENT_BUILD_PATH=$(pwd)
    - echo $PATH
    - rm -rf $HOME/golang
    - rm -rf $HOME/gopath
    - mkdir -p $HOME/golang # for GOROOT (contains the Go binary & core packages)
    - mkdir -p $HOME/gopath # for GOPATH (contains code and external packages)
    - curl https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz 2>/dev/null > go1.7.4.linux-amd64.tar.gz
    - tar -C $HOME/golang -xzf go1.7.4.linux-amd64.tar.gz
    - export GOROOT=$HOME/golang/go
    - export GOPATH=$HOME/gopath
    - export PATH=$PATH:$GOROOT/bin
    - export PATH=$PATH:$GOPATH/bin
    - (if [[ "$(go version)" == *"go version go1.7"* ]]; then echo "âœ“ Go binary installed!"; else echo "Go binary not installed"; exit -1; fi);
    - go version
    - echo $PATH
    - go env
    - which go
    - cd /builds/adi90x/go-rancher-gen
    - go get github.com/Sirupsen/logrus
    - go get github.com/BurntSushi/toml
    - go get github.com/rancher/go-rancher-metadata/metadata
    - go build 
    - ./go-rancher-gen  --version
    - mv go-rancher-gen rancher-gen
  artifacts:
    paths:
    - "rancher-gen"